Refined cookbook (#45)
* Agent config

* Global config

* Global config

* Data pipeline v1

* Eric's updates to refine cookbook

* Move function calling agent config into its own folder

* RAG Only agent

* config folder

* remove eric hardcoded vs endpoint

* respect token config in data pipeline

* Configs to a single cell

* Fix print of config

* Speed up parsing by caching the parsed table

* Fix error handling in create VS index

* REmove debug code

* Clean up uses new cookbook config

* Refactor the agent notebooks

* REmove extra init

* fix data pipeline mlflow tag

* Default to llama

* Improve debug of failed records

* Add debug code

* Simplifications

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP updates, made it partway through agent notebooks

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP debugging the function_calling_agent_mlflow_sdk.py

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP. Current state:
1) Dogfood seems to have an issue where tool calling is returning a nonexistent function name. See trace in https://e2-dogfood.staging.cloud.databricks.com/editor/notebooks/2948323364468680?o=6051921418418893#command/397386389372146
2) For RAG only agent, getting 'AttributeError: 'LLMConfig' object has no attribute 'tools'' because RAG agent config object doesn't have a tools field. See https://e2-dogfood.staging.cloud.databricks.com/editor/notebooks/2948323364468746?o=6051921418418893#command/397386389372955

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP updating pydantic config structure

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* More progress. Remaining issues:
* utils modules are not importable when agent notebooks are run directly
* Need to fix logging util
* Autologged traces and manual traces in langchain don't interleave properly

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP, more progress, remaining items:
* Restore ModelConfig across examples
* Switch back to OAI SDK
* Document tools class

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP, moving away from ModelConfig due to several devex issues

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* WIP, got most of the code to work

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* Clean up traces for langchain

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* Update documentation

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* Switch back to printing doc string, since it's cleaner than help()

Signed-off-by: Sid Murching <sid.murching@databricks.com>

* Data pipeline - refactor all utils for ease of use & ability to run in local IDE.

* Update git ignore

* locally tested tool code

* working func call agent

* remove mlflow agent

* databricks utils

* data pipeline bugs + switch to content from doc_content

* working data pipeline (except for install of utils)

* refactor agent configs to make room for genie

* removed unused code

* Genie agent

* commit for serializable model with all the old code in comments (just in case)

* remove old code from serializable model

* shared config loader

* ignore tmp configs

* tmp config readme

* initial multi agent

* multi agent works w/ function calling not tested with genie

* datapipline configs suport serializedmodel

* all agents work locally

* clean up

* add UC tool

* part 1 refactor

* tools refactor pt 2

* make function call agent work with new dirs

* agent logging works

* add tmp files to see full diff

* fc agent actually works, remove dead code agent that wasnt refactored

* rename fc agent

* rename mutli agent

* rename common to shared in agents

* move config base to __init__

* move get_current_user_info to db utils

* missing imports

* mutli agent works locally

* fix bug where is the fc agent is called by supervisor directly after another agent, it switched the last message from role=assistant to role=user

* local funcs work

* multi agent refactor for better trace & ease of understanding

* mlflow traces show supervisor COT

* improve mlflow traces

* print response vs messages info

* bug fixes in agent supervisor

* local func tracing + dict for uc tool result

* uc tool parsing code for spark exceptions

* uc tool is pytest-able

* sample sku tool works

* refactor stragglers

* fc test code

* remove rag only agent

* simplify errors

* sku translator sample tests

* tools nb

* temp nbs

* pytest

* tests for sample tools

* sample code exec tool

* data pipeline config dumps the actual uc locations

* fix set_model

* remove dependency on index's source table in vector search tool

* remove commented out code

* fix set_model and debug

* load_config  refactor

* Tools creation notebook

* Genie agent uses new config loader

* multi agent supervisor works locally

* Tool calling agent

* multi agent

* clear data pipeline outputs

* read me updates

* Multi-agent works with endpoint

* tool calling agent nb

* load config doc string

* update noteboks

* update gitignnore

* clean up readme

* remove dead code

* clean up readme

* move new openai sdk to seperate folder

* restore existing agent code

* mlflow tracing disabled hacks

* sample tools

* notebook tweaks

* load_config tweaks

* poetry env

* Tools deployment works

* Deployment logic same on all agents

---------

Signed-off-by: Sid Murching <sid.murching@databricks.com>
Co-authored-by: epec254 <epec254>
Co-authored-by: Sid Murching <sid.murching@databricks.com>